### ISSUE TITLE
Lỗi kông tìm thấy LDPlayer

### ISSUE THREAD

**Issue by sythuan92** [doanbactam/LDPlayer-Manager#1]
Hi bác, 
Nhờ bác xem giúp em lôi này
Hiện em dùng python 3.11.2
LDplayer9
Thực thi main.py gặp lỗi sauạ
Traceback (most recent call last):
  File "C:\Users\oem\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\oem\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\oem\Downloads\LDPlayer-Manager-main\LDPlayer-Manager-main\CBAutoHelper.py", line 367, in kk
    l = LDPlayer()
        ^^^^^^^^
NameError: name 'LDPlayer' is not defined

**Comment by doanbactam** [comment]
Bác check lại đường dẫn LDPLayer là được
